name: Build and Deploy

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Validate Gradle wrapper (check gradle-wrapper.jar is valid)
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle test
        run: ./gradlew test